Revert "Advisor Prod Promotion"
This reverts commit 4c0f63103bdb947637a5ba81b6ee77b3f65762a7.

It is crashlooping with

    Traceback (most recent call last):
    File "service/service.py", line 15, in <module>
    import settings
    File "/opt/app-root/src/service/settings.py", line 66, in <module>
    WEBHOOKS_TOPIC = topic('platform.notifications.ingress')
    File "/opt/app-root/src/service/settings.py", line 23, in topic
    return app_common_python.KafkaTopics[t].name
    KeyError: 'platform.notifications.ingress'

More details in https://redhat.pagerduty.com/incidents/PF5678W