Revert "Revert "Cincinnati prod: rollout f1d4ef47""
This reverts commit 98b2f0160250bd26f1d5f579a409717613636305.

We're still getting the:

  thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', cincinnati/src/lib.rs:83:38
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

panics that [1] should have fixed, so moving back to a commit that contains that.

[1]: https://github.com/openshift/cincinnati/pull/596