Re-add yamllint
Now, we specify the locale in the yamllint configuration, so that it
doesn't choke if the contents have non-ASCII characters (for instance,
a person's name).

This reverts commit bff8a303443248ef25d5f8c8d0ef7d8a2553efe0.

I have tested this by setting its value to "C", and I get:

```
 $ yamllint data/services/managed-services/cicd/saas/saas-kas-fleet-manager.yaml
Traceback (most recent call last):
  File "/bin/yamllint", line 33, in <module>
    sys.exit(load_entry_point('yamllint==1.26.0', 'console_scripts', 'yamllint')())
  File "/usr/lib/python3.9/site-packages/yamllint/cli.py", line 206, in run
    problems = linter.run(f, conf, filepath)
  File "/usr/lib/python3.9/site-packages/yamllint/linter.py", line 240, in run
    content = input.read()
  File "/usr/lib64/python3.9/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 8458: ordinal not in range(128)
```

Now, however, this file passes just fine. Also, see [this Jenkins job](https://ci.int.devshift.net/job/service-app-interface-gl-pr-check/71809/console).