Promote hive 1411793e782121c0df003d9bce467ac93fe31122
https://github.com/openshift/hive/compare/18827f64c00ea6400411366452293adf9fbecb72...1411793e782121c0df003d9bce467ac93fe31122

---
```
commit: ba62f070eb2dbd4e791fdeaafde49b91cbd67162
author: Alex Chvatal
Update pkg/controller/clusterprovision/installlogmonitor_test.go

Co-authored-by: Greg Sheremeta <greg@gregsheremeta.com>

commit: 63c533c0e62c629dba661ead70ef1c0588435166
author: Alex Chvatal
Update pkg/operator/assets/bindata.go

Co-authored-by: Greg Sheremeta <greg@gregsheremeta.com>

commit: 85eae76318d5472ac9f02811c23a3f14510fddf0
author: Alex Chvatal
Update config/configmaps/install-log-regexes-configmap.yaml

Co-authored-by: Greg Sheremeta <greg@gregsheremeta.com>

commit: ba37c6cdbf2d9b4450ca7593949287d49ea01910
author: Alex Chvatal
make update

commit: 660f48b811618cd3b349a87281114dbed640916a
author: Alex Chvatal
Update config/configmaps/install-log-regexes-configmap.yaml

Co-authored-by: Eric Fried <2uasimojo@users.noreply.github.com>

commit: 8790f09be267ca0afdac081cc04e67a24ef35e1d
author: Alex Chvatal
consolidate AWS error blocks

commit: 2b604d7473fb7873f2b844708e00050c9ff27eb0
author: Alex Chvatal
add install log regex for insufficient permissions in AWS

commit: bd69f1e27339d01c8679bb141703ae05bc46dd62
author: Alex Chvatal
add install log regex for when the subnet doesn't exist

commit: f3fb2afd340bb6e84a41be326e701bc10e1a179c
author: Alex Chvatal
Update pkg/operator/assets/bindata.go

Co-authored-by: Greg Sheremeta <greg@gregsheremeta.com>

commit: d62947c1b7f69d434b41299a396c29e6ab03e9c4
author: Alex Chvatal
Update pkg/controller/clusterprovision/installlogmonitor_test.go

Co-authored-by: Greg Sheremeta <greg@gregsheremeta.com>

commit: e4aa69d167650ebb195d0dc80cac654e287401a6
author: Alex Chvatal
Update config/configmaps/install-log-regexes-configmap.yaml

Co-authored-by: Greg Sheremeta <greg@gregsheremeta.com>

commit: 4210cb29d3306dfe14c7abc1ca687cdde6c6f220
author: Alex Chvatal
use AWS role name pattern

amazon, you lunatics

commit: 6dc55296f160c6a0ff64c9086f1b3249bfeeee23
author: Alex Chvatal
stuff from make update

commit: 48f20e45111570f3d06ec8ed5806b4254d4592c0
author: Alex Chvatal
detect install failures when IAM roles can't be deleted

commit: 25dd7ecb2563e1d3e864e37f4e1a65d545652c89
author: Abhinav Dahiya
validate username/password set for vsphere installconfig

commit: dd037dfd2000df062603c5731d9b87bd961224f8
author: Eric Fried
Update hot spares RFE

At the last minute we decided to change where `ClaimedTimestamp` lived.
Update the RFE doc for posterity.

HIVE-1576

commit: d10122b36a6e9b20a064e84e1400a125e1ae7c9e
author: Eric Fried
e2e-pool: Test broken pool CD replacement

Add a test case to e2e-pool whereby we make a CD look broken (by
patching its `ProvisionStopped` status condition to `True`) and watch
the clusterpool controller delete and replace it.

HIVE-1615

commit: 52de6793a2bc05ef04690e4aa35292cd7b585403
author: Eric Fried
ClusterPool RunningCount

Adds ClusterPool.Spec.RunningCount, the number of pool clusters to try
to keep active at any time.

Note that when ClusterPool.Spec.HibernateAfter is set, we count from
when it was claimed rather than when it was started so it doesn't
hibernate early. Adds a
ClusterDeployment.Spec.ClusterPoolref.ClaimedTimestamp to track this.

HIVE-1576

commit: 398bb08f0fcdc4bfc29a74a930667ec0182e2f7b
author: Eric Fried
ClusterPool: Register new clusters

Resolve a TODO whereby clusters added to satisfy capacity weren't being
registered in the cdCollection tracking the state of all the pool
clusters. Previously this didn't matter because there was no code after
that point that cared; we're about to add some.

Prep for HIVE-1576

commit: cc061de1c654524a72daf3048483229a50fa8c5b
author: Andrew Butcher
Update github.com/miekg/dns CVE-2019-19794.

https://github.com/advisories/GHSA-44r7-7p62-q3fr

commit: ec0ea846524d4c8cfcc206aed9a5494d60388e34
author: Eric Fried
Work around clustersync float compare test flake

We frequently see flakes like:

```
--- FAIL: TestReconcileClusterSync_NewSyncSetApplied (0.01s)
    assertion_compare.go:323:
        	Error Trace:	clustersync_controller_test.go:161
        	            				clustersync_controller_test.go:840
        	Error:      	"3599.994122811" is not greater than or equal to "3599.998926313"
        	Test:       	TestReconcileClusterSync_NewSyncSetApplied
        	Messages:   	[requeue after too small]
```

This isn't because the controller is doing something wrong; it's because
adding and substracting floating point numbers is subject to small
errors due to internal representation.

We don't really care about these requeue intervals beyond about 0.1s
granularity; so this commit truncates them to 2 decimal places to avert
this flake.

commit: b3ee879bb097c64da55eda242226f557d225da9a
author: Eric Fried
e2e-pool: Move AllClustersCurrent check into wait_for_pool_to_be_ready

We've started seeing flakes where the pool's ready/size statuses are
copacetic before the conditions settle. This commit moves the check for
AllClustersCurrent into the same loop that checks the ready/size
statuses so we get a chance to retry in this case.

commit: fd486a1b0a17d3c4e6fa941aa2fc2c435021682f
author: Abhinav Dahiya
controller/dnszone: add condition to track dns api opt-in required failures

Adds a special purpose condition to DNSZone like the
AuthenticationFailure condition to provide details when the controller
requires DNS apis to be enabled for success.

Currently, only the AWS actuator sets this condition based on request
from HIVE-1469.

The clusterdeployment controller tracks the conditions from DNSZone, and
it now also tracks the new condition to update the DNSReady condition on
the clusterdeployment.

commit: 5d4754dc12523c323ddda5438533b3917ab853ac
author: Eric Fried
e2e: Force DNSZone resync on ActuatorNotInitialized flake

We've seen frequent e2e flakes where the ClusterDeployment times out
waiting to install, and it contains a status condition like:

```
   - lastProbeTime: "2021-09-10T00:24:40Z"
      lastTransitionTime: "2021-09-10T00:24:40Z"
      message: 'error instantiating actuator: Secret "hiveci-613aa513-5fd-aws-creds" not found'
      reason: ActuatorNotInitialized
      status: "True"
      type: DNSNotReady
```

This is a timing problem whereby hiveutil create-cluster is creating the
secret and the ClusterDeployment in quick succession, and the dnszone
controller kicks in before the secret has come to life (or appeared in
the cache?). If the dnszone controller doesn't find the secret, it goes
to sleep for 2h, during which time the CD doesn't progress; and we time
out of the test after ~90m.

Since this is not a situation that could reasonably happen in real life,
we can't justify changing the logic of the clusterpool or dnszone
controllers. So with this commit we hack the test case: While waiting
for the ClusterDeployment to install, if we notice this condition, we
reset the `lastSyncGeneration` of the DNSZone object, which forces the
dnszone controller to resync it. Hopefully by this time the secret
exists and things will proceed as normal.

While we're in here, we do a couple of other small things:
- Send failure and timeout messages to stderr, which (I think?) should
make them show up in the CI output in eye-catching red, and not be
collapsed.
- On timeout, print the ClusterDeployment's status conditions so we
don't have to go hunting through the artifacts directory for them.
- Save dnszones, machinepools, and (a summary of) secrets into the
artifacts dir to aid debugging.

```