Promote saas-managed-cluster-config 2c67e9b5414e397f66610302217056af4eec0a44
https://github.com/openshift/managed-cluster-config/compare/47666bd7a29d37f97310853c6d78a3182c43382e...2c67e9b5414e397f66610302217056af4eec0a44

---
```
commit: 850164e5ea74710e1f38499a952d1dc30c10222e
author: Naveen Malik
Cannot use upper case chars in SSS name

Specifically:

```
utils.openshift_resource.ConstructResourceError: error constructing openshift resource: The SelectorSyncSet "cluster-monitoring-config-BZ1868976" is invalid: metadata.name: Invalid value: "cluster-monitoring-config-BZ1868976": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')
```

commit: 9055de3669dafd39a83d2540ac7c554ef678a770
author: Naveen Malik
on push: make generate-hive-templates

commit: 4f0fbf767f904233528d4309c8498814fd7e7968
author: Naveen Malik
Selectively disable prometheus persistence

https://issues.redhat.com/browse/OSD-5275

Better version of https://github.com/openshift/managed-cluster-config/pull/488 which also found https://issues.redhat.com/browse/CO-1188
Now directly apply the override via ext label API and work around known issues.

commit: ce6dbcbea600c1a1c9d87d5cb22b5ed395801c36
author: Naveen Malik
Enable skipping monitoring configmap management

https://issues.redhat.com/browse/OSD-5275

Caused by https://issues.redhat.com/browse/CO-1187
Needed because of https://bugzilla.redhat.com/show_bug.cgi?id=1868976

commit: 87ed9796f48e8032c02aa1321682c28182e5fc45
author: mrbarge
OHSS-1014 Increase logging resource quota to 1500GiB

commit: 26d071fac0c30c1576fb1c290386603925c851bc
author: mrbarge
OSD-5137 Add OCM_BASE_URL into MUO configmap

commit: 775ff5ca9b04134afef4e8aa3c429deaa6836260
author: mrbarge
Revert "OSD-5137 Add OCM_BASE_URL into MUO configmap"

This reverts commit 7456effbe4cc84617db40b2bc5e878ab6c52f65b.

commit: 7456effbe4cc84617db40b2bc5e878ab6c52f65b
author: mrbarge
OSD-5137 Add OCM_BASE_URL into MUO configmap

```